### ISSUE TITLE
Belt Items List Impossible Affixes

### ISSUE THREAD

**Issue by KudagFirefist** [mome-borogove/40K-enchant-viewer#2]
With the belt and secondary affix filters selected, Dmg bonus and cooldown to <skill> affixes are both listed, but in my experience and in the list of valid items these two affixes are reserved for weapons.

**Comment by mome-borogove** [comment]
These aren't incorrect, but I agree they can be a bit confusing. These do exist, but only on grenade and mine items, and "{skill}" refers to the skill provided by the belt item. Unfortunately, there isn't a straightforward way to scrape the name of that skill without importing dozens of extra config files. There's a similar problem with what looks like 4 different "damage/cd to {skill}" enchants on weapons, but those correspond to the four different skills available to weapons.

Further complicating the matter is that the enchant that provides damage/cooldown to the first skill on a weapon (i.e., `skill1_damage_percent_major` and `skill1_cooldown_percent_major`, respectively) are actually identical to the enchants on belt items. They're apparently implemented in a way that refers to whatever the first skill available on that item is. So that means I'm unable to hack something like "Cooldown Reduction for Grenade" and "Cooldown Reduction for First Weapon Skill" because they're actually the same.

Unless you have an idea for a better way we can represent these 8 enchants, I'll probably close this as "won't fix". Thanks for the feedback, though; it's good to keep me honest and ensure the tool isn't lying whenever we can avoid it.
