### ISSUE TITLE
Season 1 enchantment list incomplete

### ISSUE THREAD

**Issue by Kykuy** [mome-borogove/40K-enchant-viewer#6]
To reproduce:
1) Select "Relic", "Archeo" as enchant type
2) Set restricted to Season 1

**Comment by Kykuy** [comment]
Currently only 5 enchants are present and I know at least one that is missing, namely "+40% chance to get an Enrage token for each Inferno applied"

**Comment by Kykuy** [comment]
If you just filtered by Season=1 in enchantments.cfg, a better way to find at least some of untagged ones is to search for "_inferno" in either Name or NameID fields.

**Comment by mome-borogove** [comment]
Unfortunately, the way the game implements this is via the entries in `inventoryitems.cfg`. Doing it the correct way is a bit of a pain, since it would mean a re-write of the way we integrate item data ([notice we carry nothing but item type here](https://github.com/mome-borogove/40K-enchant-viewer/blob/3317c5b79ed3f23684c1965b139387397a9edd55/data-scripts/gen_data_js.py#L60)). Thus, the current method simply uses season flags [only from `enchantments.cfg`](https://github.com/mome-borogove/40K-enchant-viewer/blob/3317c5b79ed3f23684c1965b139387397a9edd55/data-scripts/gen_data_js.py#L67), as you point out. We could certainly modify `parse_enchants.py` to also text-match the name, add a fake seasonal tag to the enchant, and pass it up, but I avoided doing that for two reasons: (1) I'm a bit wary of enchants cropping up later with "inferno" in the name, which would almost certainly lead to a lurking bug that would stick around; and (2) nobody can play season 1 anymore, so I'm less concerned about correctness in those items.

So my strategy was basically "wait until something forces me to do inventory item parsing the right way, which will then automatically solve this problem".

If you think there's a more immediate reason to fix this (especially if something in S2 or S3 is broken because of it), I'm happy to reconsider.
