### ISSUE TITLE
Warp Heat missing from universal class resource enchants

### ISSUE THREAD

**Issue by Kykuy** [mome-borogove/40K-enchant-viewer#8]
Basically all "Focus/Adrenaline/Data-flux" enchants should be "Focus/Adrenaline/Warp Heat/Data-flux".

"-40.0% to -60.0% Focus/Adrenaline/Data-flux cost to Armour skills" just to give an actual example of current state of descriptions.

**Comment by mome-borogove** [comment]
I've always disliked this hack a bit, since it sometimes implies items exist that cannot. For instance, `godlike_datapool_per_kill` gets the string "1.0 to 2.0 Focus/Adrenaline/Data-flux gained on Kill" in the enchant viewer, but it can only roll for tech adepts. The in-game string is `{resource}`, which gets dynamically replaced by the class the player is using. Since the enchant viewer doesn't (currently) have a notion of class restrictions, we text-substitute all possible values for `{resource}` instead. The upside is that this makes items a lot easier to text-search for.

Anyways, until class context is added, I've updated the text substitution to include warp heat (because you're absolutely right that it should, if the others are).
